import random
from datetime import date
import streamlit as st

st.set_page_config(page_title="Ready, Set, Choose!", page_icon="🧩", layout="wide")

st.markdown("""
<style>
:root{color-scheme:light!important}.stApp{background:linear-gradient(180deg,#fffaf2,#eef7ff);color:#172033}.block-container{max-width:1150px;padding-top:1.4rem}h1,h2,h3{color:#173b65!important}.stApp p,.stApp li,.stApp label,.stApp [data-testid="stMarkdownContainer"],.stApp [data-testid="stWidgetLabel"] p{color:#172033!important}.hero,.panel,.choice{background:#fff;border:2px solid #93c5fd;border-radius:18px;padding:18px;box-shadow:0 7px 20px #1e40af14}.choice{min-height:205px;border-color:#c7d2fe}.choice h3{color:#174a7e!important}.pill{display:inline-block;border-radius:999px;background:#e0f2fe;color:#075985;padding:.2rem .55rem;margin:.12rem .15rem;font-size:.78rem;font-weight:800}.task-visual{display:flex;align-items:center;justify-content:center;min-height:92px;margin:4px 0 12px;border-radius:16px;background:linear-gradient(135deg,#dbeafe,#fef3c7);border:2px solid #bfdbfe;font-size:3.25rem;letter-spacing:.2rem}.panel .task-visual{max-width:420px;min-height:110px;font-size:4rem}.step{background:#eff6ff;border-left:5px solid #2563eb;border-radius:9px;padding:10px 13px;margin:8px 0}.adult{background:#fff7ed;border:2px solid #fdba74;border-radius:13px;padding:12px 14px}
</style>""", unsafe_allow_html=True)

def t(i,title,modes,materials,mins,goal,steps,adult,easy,hard,link):
    return dict(id=i,title=title,modes=modes,materials=materials,minutes=mins,goal=goal,steps=steps,adult=adult,easy=easy,hard=hard,link=link)

TASKS=[
 t("breathe","Trace, Breathe, and Pause",["Regulate & Focus"],["paper","pencils"],5,"Visual attention and calm breathing",["Trace a large circle slowly.","Breathe in going up and out going down.","Color the circle."],"Model one circle with a quiet voice.","Guide the hand or trace beside the student.","Add a repeating pattern inside the circle.","Use team colors if motivating."),
 t("colors","Color Sort",["Regulate & Focus","Participate"],["crayons","paper"],8,"Visual discrimination and sorting",["Draw two or three spaces.","Choose colors.","Place matching marks in the correct space."],"Offer only two colors if needed.","Use two colors and accept pointing.","Sort four colors and explain a match.","Sort sports or team colors."),
 t("same","Same or Different?",["Regulate & Focus","Participate"],["classroom objects","paper","pencils"],8,"Comparing features",["Place two objects together.","Ask same, different, or both.","Draw or point to the answer."],"Accept eye gaze, pointing, or speech.","Use only one comparison.","Name a similarity and a difference.","Compare sports pictures or numbers."),
 t("pattern","Quiet Pattern Maker",["Regulate & Focus","Participate"],["paper","markers"],10,"Repeating patterns and attention",["Make a dot-line pattern.","Continue it across the page.","Pause whenever needed."],"Start the pattern and invite one mark.","Use AB only.","Create AAB or ABB.","Use team colors or score marks."),
 t("groups","Build a Group",["Participate","Practice"],["counters","blocks","paper"],10,"Counting and grouping",["Choose a number 1–10.","Build that many objects.","Circle or write the number."],"Count together with a number card.","Use 1–5.","Make two groups and compare them.","Build a team lineup."),
 t("sticky","Sticky Note Count",["Participate","Practice"],["sticky notes","paper","pencils"],10,"Counting and recording",["Place 1–10 sticky notes.","Touch-count each one.","Choose the matching number."],"Limit the range to 1–5.","Count with an adult.","Make two amounts and compare.","Make a two-team scoreboard."),
 t("sort","Sort and Tell",["Participate","Practice"],["buttons or counters","paper"],12,"Categorizing by an attribute",["Choose color, size, or shape.","Make groups.","Tell or show the rule."],"Give the rule first.","Sort by one rule only.","Resort by a second rule.","Sort team colors or positions."),
 t("dice","Roll, Count, Compare",["Participate","Practice","Stretch"],["dice","paper","pencils"],12,"Comparing quantities",["Roll a die.","Record the number.","Roll again and show which is more."],"Use one die and dot patterns.","Compare two rolls.","Roll two dice, add, and compare.","Treat rolls as team scores."),
 t("cards","Put Cards in Order",["Participate","Practice","Stretch"],["playing cards","paper"],15,"Ordering numbers",["Choose 3–5 number cards.","Put them least to greatest.","Point to first and last."],"Use cards 1–5 only.","Order three cards.","Order seven and find the middle.","Make a finishing-order list."),
 t("blocks","Build My Model",["Participate","Practice"],["blocks"],12,"Following a visual model",["Adult builds a small model.","Student copies it.","Compare the models."],"Use two blocks.","Match color or position.","Student gives directions to rebuild it.","Build a stadium or podium."),
 t("clayshape","Clay Shape Shop",["Participate","Practice","Stretch"],["clay or Play-Doh","paper"],15,"Fine-motor work and shapes",["Make a ball, snake, and pancake.","Match each to a drawing.","Decorate one."],"Adult rolls clay if needed.","Make one shape.","Make a triangle or pattern.","Make a ball, jersey, trophy, or number."),
 t("claynum","Make the Number",["Participate","Practice"],["clay or Play-Doh","paper"],12,"Number recognition",["Choose a number.","Roll a clay snake.","Form and trace the number."],"Use one large number.","Copy an adult-made number.","Make two and compare them.","Make a favorite jersey number."),
 t("measure","Measure Classroom Objects",["Practice","Stretch"],["ruler","pencils","paper","classroom objects"],15,"Comparing length",["Choose three safe objects.","Measure each.","Record or draw short, medium, long."],"Use comparison words instead of numbers.","Choose short and long.","Order measurements and find a difference.","Compare cards or score sheets."),
 t("graph","Sticker or Mark Graph",["Practice","Stretch"],["paper","sticky notes","pencils"],15,"Representing categories",["Choose 2–3 answer categories.","Ask a question.","Add one mark per answer."],"Use two categories and adult answers.","Make two columns.","Label and find the most.","Graph favorite sports or colors."),
 t("frequency","Make a Counting Table",["Practice","Stretch"],["paper","pencils","counters"],18,"Organizing category counts",["Draw category boxes.","Place one counter per item.","Count and record totals."],"Adult draws boxes and names categories.","Use two categories.","Compare categories with counts.","Make a one-way frequency table."),
 t("sequence","What Comes Next?",["Participate","Practice","Stretch"],["index cards","markers","paper"],12,"Sequencing",["Draw three routine steps.","Mix the cards.","Put them in order."],"Use gestures or pictures.","Use two steps.","Create a four- or five-step sequence.","Sequence a game or scoring routine."),
 t("collage","My Choice Collage",["Participate","Practice"],["paper","crayons","markers","glue"],20,"Communicating preferences",["Choose three things you like.","Draw or write them.","Arrange them on one page."],"Offer two options at a time.","Choose one thing.","Sort like, unsure, and not for me.","Include sports, teams, numbers, or colors."),
 t("hunt","Classroom Number Hunt",["Participate","Practice","Stretch"],["paper","pencils","classroom objects"],15,"Recognizing numbers",["Find three classroom numbers.","Point, copy, or draw them.","Put them in order."],"Adult points out the first.","Find one number.","Find five and identify greatest.","Find numbers on books or calendars."),
 t("story","Roll a Tiny Story",["Practice","Stretch"],["dice","paper","pencils"],15,"Using numbers in a story",["Roll for how many objects.","Roll for more or fewer.","Draw and solve with counters."],"Adult narrates the story.","Use addition within 5.","Write a sports score story.","Use a team score narrative."),
 t("draw","Listen and Draw",["Participate","Practice"],["paper","pencils","crayons"],12,"Following directions",["Complete one drawing direction.","Add a second direction.","Show the finished picture."],"Use gestures and model after trying.","Follow one direction.","Follow three linked directions.","Draw a court or scoreboard."),
 t("tally","Quiet Tally Marks",["Regulate & Focus","Participate"],["paper","pencils"],8,"Repeated motor action and counting",["Make groups of five tally marks.","Pause after each group.","Count the total."],"Dots may replace tally marks.","Make one group.","Record two groups and compare.","Tally colors, teams, or symbols."),
 t("free","Build Something You Choose",["Regulate & Focus","Participate","Practice"],["clay or Play-Doh"],15,"Choice and sustained engagement",["Choose what to build.","Build for five minutes.","Show or name one part."],"Offer two ideas if needed.","Copy a simple model.","Use patterns or named shapes.","Build a sports object or trophy."),
 t("symbols","Letter or Number Sort",["Regulate & Focus","Participate"],["index cards","markers","paper"],10,"Visual sorting",["Write or use letter and number cards.","Make two groups.","Place each card correctly."],"Use three cards at a time.","Sort letters and numbers.","Sort odd/even or vowels/consonants.","Use jersey numbers and initials."),
 t("target","Draw the Target",["Regulate & Focus","Participate","Practice"],["paper","markers","pencils"],12,"Visual-motor control",["Draw a three-section target.","Color each section.","Point to center and outside."],"Adult draws the target first.","Color two sections.","Add point values and choose a score.","Use sports-style point values."),
 t("reset","Choose Your Reset",["Regulate & Focus"],["paper","crayons"],5,"Communicating a regulation preference",["Choose draw, breathe, stretch, or quiet look.","Do it for two minutes.","Show finished, more, or stop."],"Honor the choice and keep language minimal.","Adult offers two choices.","Student leads the adult through the reset.","Decorate a team-color breathing card."),
]

# The first bank above contains reusable prototypes. This student-facing bank
# replaces vague directions with concrete quantities, materials, and finish lines.
def detailed(item, finish=None):
    # Detailed tasks store their completion sentence in the final `t()` field.
    # Accepting it here keeps every task entry compact and prevents deployment errors.
    if finish is None:
        finish = item["link"]
        item["link"] = "Use sports colors, scores, or team names only if that helps motivate the student."
    item["finish"] = finish
    return item

TASKS = [
 detailed(t("crayon_sort","Sort 12 Crayons",["Regulate & Focus","Participate"],["paper","crayons"],15,"Sort objects by color and count each group",["Get 12 crayons: 4 red, 4 blue, and 4 yellow.","Draw 3 large circles on a piece of paper.","Write RED, BLUE, and YELLOW above the circles.","Put each crayon in the circle with the same color.","Touch-count the crayons in each circle and tell the adult the numbers."],"Put the 12 crayons in a small pile. Point to one crayon at a time and help only when needed.","Use 6 crayons: 2 red, 2 blue, and 2 yellow.","Write the total number of crayons in all 3 circles.","This is finished when every crayon is in a labeled circle and each group has a number.")),
 detailed(t("block_towers","Build 3 Block Towers",["Participate","Practice"],["blocks","paper","pencils"],15,"Count blocks and compare tower heights",["Get 6 blocks.","Build Tower 1 with 1 block.","Build Tower 2 with 2 blocks.","Build Tower 3 with 3 blocks.","Draw the 3 towers on paper.","Circle the tallest tower."],"Place one block at a time beside the student and count aloud.","Build only Tower 1 and Tower 2.","Build a fourth tower with 4 blocks and label it.","This is finished when 3 towers are standing, drawn, and the tallest is circled.")),
 detailed(t("dice_tally","Roll a Die 10 Times",["Participate","Practice"],["dice","paper","pencils"],15,"Record results with tally marks",["Draw 6 boxes on paper and label them 1, 2, 3, 4, 5, and 6.","Roll the die 10 times.","After each roll, make one tally mark in the matching box.","Count the tally marks in every box.","Circle the box with the most marks."],"Roll the die for the student and let the student place each tally.","Roll 5 times using only numbers 1–3 if needed.","Roll 20 times and write the total in each box.","This is finished when 10 rolls are recorded and the box with the most is circled.")),
 detailed(t("clay_shapes","Make 3 Clay Shapes",["Participate","Practice"],["clay or Play-Doh","paper","pencils"],15,"Make and identify basic shapes",["Get 3 small pieces of clay.","Make Piece 1 into a ball.","Make Piece 2 into a long snake.","Flatten Piece 3 into a pancake.","Draw the ball, snake, and pancake on paper.","Point to each shape when the adult names it."],"Make one shape at a time and demonstrate before asking the student to copy.","Make only a ball and a snake.","Use clay to make a triangle, square, and circle.","This is finished when all 3 clay shapes are made and matched to drawings.")),
 detailed(t("card_order","Put Number Cards 1–10 in Order",["Participate","Practice","Stretch"],["playing cards","paper"],20,"Put numbers in order from smallest to largest",["Take the cards A, 2, 3, 4, 5, 6, 7, 8, 9, and 10.","Use A as the number 1.","Place all 10 cards face up.","Move the cards until they show 1 through 10 in order.","Point to the first card and say 1.","Point to the last card and say 10."],"Remove face cards and help the student find the next number.","Use only cards A through 5.","Turn the cards face down, choose 5, and put them in order from memory.","This is finished when the 10 cards show 1, 2, 3, 4, 5, 6, 7, 8, 9, 10.")),
 detailed(t("counter_match","Match Numbers to Counters",["Participate","Practice"],["paper","pencils","counters"],15,"Match a written number to an amount",["Write the numbers 1, 2, 3, 4, and 5 in 5 boxes.","Put 1 counter under the 1.","Put 2 counters under the 2.","Continue until every number has its matching amount.","Touch-count each row."],"Make the boxes and count the first row with the student.","Use only numbers 1, 2, and 3.","Make a second set using numbers 6 through 10.","This is finished when all 5 numbers have the correct number of counters underneath.")),
 detailed(t("measure_pencils","Measure 3 Pencils",["Practice","Stretch"],["ruler","pencils","paper"],15,"Measure objects and compare lengths",["Get 3 pencils.","Line each pencil up with the zero on the ruler.","Write the length of each pencil in inches.","Draw the 3 pencils from shortest to longest.","Circle the longest pencil."],"Hold the ruler steady and accept short, medium, and long if numbers are difficult.","Compare only 2 pencils.","Find how many inches longer the longest pencil is than the shortest.","This is finished when all 3 pencils have measurements and the longest is circled.")),
 detailed(t("sticky_graph","Make a 2-Column Color Graph",["Practice","Stretch"],["paper","sticky notes","pencils"],20,"Make a simple graph from 10 choices",["Draw 2 columns on paper and label them RED and BLUE.","Get 10 sticky notes.","Place 4 notes in RED and 6 notes in BLUE.","Count the notes in each column.","Write the number at the bottom of each column.","Circle the column with more notes."],"Use 2 notes in each column first, then add more.","Use 2 red and 2 blue notes.","Ask classmates for their real color choices and graph the answers.","This is finished when both columns are labeled, counted, and the larger column is circled.")),
 detailed(t("pattern_blocks","Copy an A-B Block Pattern",["Regulate & Focus","Participate","Practice"],["blocks","paper","pencils"],15,"Copy and continue a repeating pattern",["Get 6 blocks: 3 of one color and 3 of another color.","Adult builds a pattern: red, blue, red, blue.","Copy the first 4 blocks.","Add 2 more blocks to continue the pattern.","Draw the finished pattern on paper."],"Use only 2 blocks first and let the student copy one pair.","Copy red-blue once.","Make an A-B-B pattern and explain what comes next.","This is finished when the student copies 4 blocks, adds 2, and draws the pattern.")),
 detailed(t("draw_shapes","Draw 5 Shapes from Directions",["Participate","Practice"],["paper","pencils","crayons"],15,"Follow short directions and identify shapes",["Draw 1 large circle.","Draw 1 square under the circle.","Draw 1 triangle beside the square.","Draw 1 star above the circle.","Draw 1 rectangle next to the triangle.","Color the circle blue and the square red."],"Give one direction, wait, then give the next direction.","Draw only the circle, square, and triangle.","Add position words such as left, right, above, and below.","This is finished when all 5 shapes are present and the circle and square are colored.")),
 detailed(t("button_sort","Sort 10 Buttons by Size",["Regulate & Focus","Participate"],["buttons or counters","paper"],15,"Sort objects into big and small groups",["Get 10 buttons: 5 big and 5 small.","Draw 2 circles on paper.","Label one circle BIG and one circle SMALL.","Place each button in the correct circle.","Count the buttons in each circle."],"Use 4 buttons and physically show the size difference.","Sort 2 big and 2 small buttons.","Sort the same buttons by color after sorting by size.","This is finished when all 10 buttons are in a labeled circle and both groups are counted.")),
 detailed(t("frequency_table","Make a 1-Way Counting Table",["Practice","Stretch"],["paper","pencils","counters"],20,"Separate categories and record frequencies",["Draw 3 rows labeled STAR, CIRCLE, and TRIANGLE.","Get 10 counters: 4 star cards, 3 circle cards, and 3 triangle cards.","Put each counter in the matching row.","Count each row.","Write the count next to each label.","Circle the row with the greatest count."],"Draw the rows and place one item at a time with the student.","Use 2 categories with 2 items each.","Add a total row and check that the total is 10.","This is finished when all 10 items are sorted, counted, and recorded.")),
 detailed(t("clay_number","Make and Match 3 Numbers",["Participate","Practice"],["clay or Play-Doh","paper","pencils"],15,"Form numbers and match them to written numbers",["Write 3, 6, and 9 on paper.","Make a clay snake.","Use the snake to form the number 3.","Make the number 6.","Make the number 9.","Place each clay number beside its matching written number."],"Make one number at a time and use a large model.","Make only the number 3.","Make numbers 3, 6, 9, and put them from least to greatest.","This is finished when clay 3, 6, and 9 are next to the matching written numbers.")),
 detailed(t("choice_collage","Draw Your Favorite Color, Number, and Activity",["Participate","Practice"],["paper","crayons","markers"],20,"Show three personal preferences",["Adult draws 3 large boxes on one piece of paper.","In Box 1, use a crayon to show your favorite color.","In Box 2, write or trace your favorite number.","In Box 3, draw your favorite sport, game, or classroom activity.","Point to the box you like best."],"Offer two choices for each box and let the student point.","Complete only Box 1 for favorite color.","Write one sentence under each box with adult help.","This is finished when all 3 boxes show a favorite color, number, and activity.")),
 detailed(t("calm_tally","Make 5 Groups of 5 Tally Marks",["Regulate & Focus","Participate"],["paper","pencils"],15,"Use repeated marks and count groups",["Draw 5 boxes on paper.","Put 5 tally marks in Box 1.","Put 5 tally marks in Box 2.","Repeat until all 5 boxes have 5 marks.","Touch-count one box with the adult."],"Make one box at a time and offer a short pause between boxes.","Make 2 boxes with 5 marks each.","Count all 25 marks and write 25.","This is finished when all 5 boxes have exactly 5 marks.")),
 detailed(t("number_trace","Trace Numbers 1–10",["Regulate & Focus","Participate","Practice"],["paper","pencils","crayons"],15,"Recognize and form numbers",["Adult writes large dotted numbers 1 through 10 on paper.","Trace each number with a pencil.","Choose one crayon and trace the numbers again.","Point to each number while the adult says it."],"Make the dotted numbers before giving the page to the student.","Trace numbers 1 through 5 only.","Write numbers 1 through 10 once without dots.","This is finished when every assigned number has been traced twice.")),
 detailed(t("shape_grid","Copy 9 Shapes",["Participate","Practice"],["paper","pencils","crayons"],15,"Copy basic shapes into matching spaces",["Adult draws a 3-by-3 grid.","Adult draws a circle, square, and triangle in the top row.","Copy the same 3 shapes in the middle row.","Copy them again in the bottom row.","Color every circle blue."],"Draw large shapes and point to the next empty box.","Use a 2-by-2 grid with circles and squares.","Add rectangles and stars to make a 4-by-3 grid.","This is finished when all 9 boxes contain the correct shape and all circles are blue.")),
 detailed(t("dot_cards","Make Number Dot Cards",["Participate","Practice"],["index cards","markers","counters"],20,"Match numerals to dot quantities",["Get 5 index cards.","Write 1, 2, 3, 4, and 5 on the cards.","Turn each card over.","Draw the matching number of dots on the back.","Place the cards in order and check each dot group with counters."],"Write the numbers for the student and count each dot together.","Make cards 1 through 3.","Make cards 1 through 10.","This is finished when every card has a numeral on one side and the matching dots on the other.")),
 detailed(t("line_paths","Trace 6 Lines from a Dot to a Star",["Regulate & Focus","Participate"],["paper","pencils","markers"],15,"Trace six different lines with a pencil",["Adult draws 6 separate lines on paper: straight, curved, zigzag, loop, stair-step, and wavy.","Adult draws a large dot at the beginning of every line and a star at the end.","Put your pencil on the first dot.","Trace directly over the line until you reach the star.","Repeat until all 6 lines are traced, then circle the easiest line."],"Use thick marker lines and one path at a time.","Draw and trace only 3 wide lines: straight, curved, and wavy.","Trace all 6 lines backward from the star to the dot.","This is finished when pencil marks connect every dot to its matching star.")),
 detailed(t("name_count","Count the Letters in a Name",["Participate","Practice"],["paper","pencils","counters"],15,"Connect letters with counting",["Write the student's first name in large letters.","Place one counter under each letter.","Touch each counter and count the letters.","Write the total beside the name.","Circle the first letter."],"Write the name for the student and move one counter at a time.","Use a short familiar word instead of the full name.","Compare the number of letters in two names.","This is finished when every letter has one counter and the total is written.")),
 detailed(t("picture_sequence","Draw a 4-Step School Routine",["Participate","Practice","Stretch"],["paper","pencils","crayons"],20,"Put familiar events in order",["Fold paper into 4 boxes.","In Box 1 draw entering class.","In Box 2 draw sitting down.","In Box 3 draw doing work.","In Box 4 draw cleaning up.","Point to the boxes in order."],"Describe one box at a time and accept simple stick figures.","Use 2 boxes: start work and finish work.","Write First, Next, Then, Last above the boxes.","This is finished when all 4 boxes show the routine in order.")),
 detailed(t("finish_pattern","Finish 8 Patterns",["Participate","Practice","Stretch"],["paper","pencils","crayons"],15,"Identify what comes next in a pattern",["Adult draws 8 short patterns with one blank at the end.","Use shapes or colors, such as circle-square-circle-blank.","Look at Pattern 1 and draw what comes next.","Complete all 8 patterns.","Check each answer with the adult."],"Use AB patterns and complete one at a time.","Complete 4 AB patterns.","Include AAB, ABB, and ABC patterns.","This is finished when every blank has the correct next item.")),
 detailed(t("card_pairs","Find 5 Matching Card Pairs",["Regulate & Focus","Participate","Practice"],["playing cards"],15,"Match equal numbers",["Get 2 cards for each number from 1 through 5.","Mix the 10 cards face up.","Find the two 1 cards and place them together.","Continue until all 5 pairs are together.","Count the completed pairs."],"Place one card from each pair in a row as a visual guide.","Use 3 pairs.","Turn the cards face down and play a memory game.","This is finished when all 10 cards are arranged as 5 matching pairs.")),
 detailed(t("red_black","Sort 20 Cards by Color",["Participate","Practice"],["playing cards","paper"],15,"Sort cards into red and black categories",["Choose 20 playing cards without jokers.","Place one paper labeled RED and one labeled BLACK on the table.","Look at one card at a time.","Place it under the correct label.","Count and record each group."],"Use 10 cards and point out the first red and black examples.","Sort 8 cards without recording totals.","Compare the totals and find the difference.","This is finished when all cards are sorted and both totals are written.")),
 detailed(t("high_card","Play 10 High-Card Rounds",["Participate","Practice","Stretch"],["playing cards","paper","pencils"],20,"Compare two numbers",["Remove face cards and shuffle the number cards.","Turn over 2 cards.","Point to the greater number.","Give one tally mark to the greater card's side.","Repeat for 10 rounds and count the tallies."],"Use cards 1 through 5 and say both numbers aloud.","Play 5 rounds.","Include ties and write greater than, less than, or equal.","This is finished when 10 rounds are played and both tally totals are counted.")),
 detailed(t("roll_build","Roll and Build 8 Towers",["Participate","Practice"],["dice","blocks","paper","pencils"],20,"Connect dice quantities to constructed sets",["Roll one die.","Build a tower with that many blocks.","Draw the tower and write the number.","Take the tower apart.","Repeat until 8 towers have been built and drawn."],"Adult counts the blocks aloud with the student.","Build 4 towers.","Use two dice and build the total.","This is finished when 8 rolls each have a matching tower, drawing, and number.")),
 detailed(t("dice_add","Add 10 Dice Rolls",["Practice","Stretch"],["dice","paper","pencils","counters"],20,"Model and solve simple addition",["Roll 2 dice.","Build each number with counters.","Push the groups together.","Count the total and write the addition sentence.","Repeat for 10 addition problems."],"Use one die twice and totals no greater than 6.","Complete 5 addition problems.","Solve without counters after checking the first 3.","This is finished when all assigned rolls have a drawing or model and an answer.")),
 detailed(t("block_stairs","Build Block Stairs 1–5",["Participate","Practice"],["blocks","paper","pencils"],15,"Build increasing quantities",["Get 15 blocks.","Build Step 1 with 1 block.","Build Step 2 with 2 blocks.","Continue through Step 5 with 5 blocks.","Draw the staircase and label each step."],"Hand the student the exact blocks needed for each step.","Build Steps 1 through 3.","Continue the staircase through Step 7.","This is finished when the five steps contain 1, 2, 3, 4, and 5 blocks.")),
 detailed(t("equal_groups","Make 4 Equal Groups",["Practice","Stretch"],["counters","paper","pencils"],20,"Divide objects into equal groups",["Get 12 counters.","Draw 4 circles on paper.","Place one counter in each circle until all counters are used.","Count each circle.","Write 3 inside every circle and write 12 total."],"Use 6 counters and 2 circles.","Make 2 groups of 3.","Try 15 counters in 5 equal groups.","This is finished when all counters are used and every group has the same amount.")),
 detailed(t("more_less","Make More, Less, and Equal",["Participate","Practice"],["counters","paper","pencils"],15,"Compare two quantities",["Draw 3 pairs of boxes.","In Pair 1 place 5 counters on the left and 2 on the right; circle more.","In Pair 2 place 1 on the left and 4 on the right; circle less.","In Pair 3 place 3 in each box; circle equal.","Touch-count every group."],"Complete one pair at a time and read the comparison word aloud.","Use only the more and equal pairs.","Write >, <, or = between each pair.","This is finished when all 3 pairs are built and the correct comparison is circled.")),
 detailed(t("ten_frame","Fill 5 Ten-Frames",["Participate","Practice"],["paper","pencils","counters"],20,"Represent numbers within 10",["Adult draws 5 ten-frames.","Write 2, 4, 6, 8, and 10 beside them.","Fill the first frame with 2 counters.","Continue until every frame matches its number.","Touch-count one completed frame."],"Use frames for 2 and 4 only.","Complete 3 frames.","Write how many empty spaces remain in each frame.","This is finished when all 5 frames contain the requested number of counters.")),
 detailed(t("clay_letters","Make 4 Clay Letters",["Participate","Practice"],["clay or Play-Doh","paper","pencils"],15,"Form familiar letters",["Write the student's first initial and 3 other familiar letters on paper.","Roll clay into thin snakes.","Form the first letter on top of the written model.","Repeat for all 4 letters.","Point to the student's initial."],"Choose letters made mostly with straight lines.","Make 2 letters.","Make the letters without placing clay on a model.","This is finished when all 4 clay letters match the written models.")),
 detailed(t("clay_sizes","Make 9 Clay Balls by Size",["Regulate & Focus","Participate","Practice"],["clay or Play-Doh","paper"],15,"Compare small, medium, and large",["Make 3 small clay balls.","Make 3 medium clay balls.","Make 3 large clay balls.","Draw 3 circles labeled SMALL, MEDIUM, and LARGE.","Place each ball beside its matching label."],"Make one example of each size first.","Make 1 ball of each size.","Order all 9 balls from smallest to largest.","This is finished when 9 balls are sorted into 3 labeled size groups.")),
 detailed(t("clay_pattern","Make a 9-Piece Clay Pattern",["Participate","Practice","Stretch"],["clay or Play-Doh","paper"],20,"Create and continue a repeating pattern",["Make 3 clay balls, 3 clay snakes, and 3 clay pancakes.","Place them in this order: ball, snake, pancake.","Repeat that order 3 times.","Draw the pattern on paper.","Point to what would come next."],"Adult makes the first three pieces as a model.","Repeat ball-snake 3 times.","Create a different three-part pattern.","This is finished when 9 clay pieces form 3 complete repeats.")),
 detailed(t("emotion_faces","Make 3 Clay Faces",["Regulate & Focus","Participate"],["clay or Play-Doh","paper","pencils"],20,"Identify and communicate emotions",["Make 3 flat clay circles for faces.","Give Face 1 a smile.","Give Face 2 a straight mouth.","Give Face 3 a frown.","Write or copy HAPPY, CALM, and SAD on paper.","Match each face to a word."],"Model each mouth and accept pointing instead of naming.","Make happy and sad faces only.","Add eyes and eyebrows that match each feeling.","This is finished when 3 faces are matched to the 3 emotion words.")),
 detailed(t("sticky_line","Build a Sticky-Note Number Line",["Participate","Practice"],["sticky notes","markers","paper"],20,"Put numbers in sequence",["Get 10 sticky notes.","Write one number from 1 to 10 on each note.","Mix the notes.","Place them in a straight line from 1 to 10.","Touch each note and count forward."],"Write the numbers for the student and provide 1 and 10 as anchors.","Use numbers 1 through 5.","Count backward from 10 to 1.","This is finished when all 10 notes are in order in one straight line.")),
 detailed(t("sticky_categories","Sort 12 Picture Notes",["Participate","Practice"],["sticky notes","markers","paper"],20,"Sort pictures into categories",["Draw 4 food pictures, 4 animal pictures, and 4 school-item pictures on sticky notes.","Label 3 areas FOOD, ANIMALS, and SCHOOL.","Move each note to the matching area.","Count each category.","Write 4 beside every category."],"Draw simple pictures before giving the notes to the student.","Use 2 categories with 3 pictures each.","Add one new picture to each category and update the totals.","This is finished when all 12 notes are sorted and every category is counted.")),
 detailed(t("book_sort","Sort 8 Books by Size",["Participate","Practice"],["classroom objects","paper","pencils"],15,"Compare and order object sizes",["Choose 8 classroom books.","Place them from shortest to tallest.","Draw the shortest book.","Draw the tallest book.","Write SHORT and TALL under the drawings."],"Use 3 books with obvious size differences.","Sort 4 books.","Measure each book and record its height.","This is finished when all 8 books are ordered and the shortest and tallest are drawn.")),
 detailed(t("pencil_sort","Sort 12 Pencils Two Ways",["Practice","Stretch"],["pencils","paper"],20,"Sort the same objects using different rules",["Get 12 pencils with different colors or lengths.","First sort them by color.","Draw the color groups and record each count.","Mix the pencils again.","Sort them by short and long.","Record both new counts."],"Use 6 pencils and complete only the color sort first.","Sort 6 pencils one way.","Explain which sorting rule created more groups.","This is finished when the same pencils have been sorted and counted in two different ways.")),
 detailed(t("paper_strips","Order 6 Paper Strips",["Participate","Practice"],["paper","scissors","glue"],20,"Order objects by length",["Adult cuts 6 paper strips of clearly different lengths.","Mix the strips.","Place them from shortest to longest.","Glue them to paper in that order.","Write 1 under the shortest and 6 under the longest."],"Use 3 strips and help align the left edges.","Order and glue 3 strips.","Measure and label every strip.","This is finished when all strips are glued from shortest to longest.")),
 detailed(t("cut_shapes","Cut and Sort 9 Shapes",["Participate","Practice"],["paper","scissors","crayons","glue"],20,"Identify and sort shapes",["Adult draws 3 circles, 3 squares, and 3 triangles.","Color the circles blue, squares red, and triangles yellow.","Cut out the 9 shapes.","Glue like shapes together in 3 groups.","Count each group."],"Use child-safe scissors and assist with turning the paper.","Use 2 circles and 2 squares.","Arrange the shapes in a repeating pattern before gluing.","This is finished when 9 colored shapes are cut, grouped, glued, and counted.")),
 detailed(t("folder_tally","Tally 10 Classroom Colors",["Practice","Stretch"],["classroom objects","paper","pencils"],20,"Collect and record categorical data",["Choose 10 folders, notebooks, or book covers.","Make rows for RED, BLUE, GREEN, and OTHER.","Look at one item at a time.","Make one tally in the matching row.","Count each row and circle the greatest frequency."],"Adult selects the 10 items and points to the color rows.","Use 6 items and 2 color rows.","Turn the tallies into a bar graph.","This is finished when 10 items are tallied and every row has a total.")),
 detailed(t("coin_sort","Sort and Count 20 Coins",["Participate","Practice","Stretch"],["coins","paper","pencils"],20,"Sort objects by type and count frequencies",["Get 20 classroom coins or coin counters.","Label areas PENNY, NICKEL, DIME, and QUARTER.","Sort one coin at a time.","Count and record each group.","Check that the four counts total 20."],"Use 10 coins and only pennies and nickels.","Sort 6 coins into 2 groups.","Find the total value of each group.","This is finished when all 20 coins are sorted, counted, and checked.")),
 detailed(t("eraser_groups","Make Groups with 16 Erasers",["Practice","Stretch"],["erasers or counters","paper","pencils"],20,"Model equal groups and multiplication",["Get 16 erasers or counters.","Draw 4 circles.","Share the objects one at a time among the circles.","Count each group.","Write 4 groups of 4 and 16 total."],"Use 8 objects and 2 circles.","Make 2 groups of 4.","Rearrange 16 as 2 groups of 8 and compare.","This is finished when 16 objects are divided evenly and the grouping is recorded.")),
 detailed(t("classroom_shapes","Find 8 Classroom Shapes",["Participate","Practice"],["paper","pencils","classroom objects"],20,"Recognize shapes in real objects",["Draw boxes labeled CIRCLE, SQUARE, RECTANGLE, and TRIANGLE.","Find 2 classroom objects for each shape.","Draw each object in the correct box.","Count the drawings in every box.","Show one object to the adult."],"Adult names possible objects and student chooses where they belong.","Find 1 circle and 1 rectangle.","Write the object names under the drawings.","This is finished when 8 objects are drawn in the correct shape boxes.")),
 detailed(t("number_collage","Make a Number 10 Collage",["Participate","Practice"],["paper","markers","sticky notes","glue"],20,"Represent one number in several ways",["Write a large 10 in the center of the paper.","Draw 10 dots in one corner.","Place 10 sticky notes around the number.","Make 2 groups of 5 marks.","Write TEN at the bottom."],"Adult prepares the large number and counts each group aloud.","Use the number 5 with 5 dots and 5 notes.","Add an addition sentence that equals 10.","This is finished when the page shows 10 as a numeral, word, dots, notes, and groups.")),
 detailed(t("score_compare","Compare 8 Simple Scores",["Practice","Stretch"],["paper","pencils","playing cards"],20,"Compare numbers using a sports theme",["Draw 8 rows with TEAM A and TEAM B.","Turn over 2 number cards for Row 1.","Write one score under each team.","Circle the greater score.","Repeat for all 8 rows."],"Use cards 1 through 5 and read both scores aloud.","Complete 4 rows.","Write the score difference in every row.","This is finished when 8 score pairs are recorded and every greater score is circled.")),
 detailed(t("paper_scoreboard","Build a Paper Scoreboard",["Participate","Practice","Stretch"],["paper","pencils","markers","dice"],20,"Record changing totals",["Write HOME and AWAY at the top of paper.","Start both scores at 0.","Roll the die for HOME and add that number.","Roll for AWAY and add that number.","Record 5 rounds and circle the final winner."],"Use tally marks instead of addition and count at the end.","Complete 3 rounds using tallies.","Find the winning margin after 5 rounds.","This is finished when 5 rounds and both final scores are recorded.")),
 detailed(t("design_jersey","Design a Paper Jersey",["Participate","Practice","Stretch"],["paper","pencils","crayons","markers"],20,"Create a design using colors, numbers, and shapes",["Adult draws a large T-shirt shape on paper.","Choose 2 colors for the jersey.","Choose 1 number and write it in the center.","Add 3 shapes as decorations.","Color the entire jersey and show the finished design."],"Offer two colors and two numbers to choose from.","Use one color, one number, and one shape.","Create a matching front and back with a name and number.","This is finished when the jersey has 2 colors, 1 number, and 3 shapes.")),
 detailed(t("pattern_flag","Create a Pattern Flag",["Participate","Practice","Stretch"],["paper","pencils","crayons","markers"],20,"Create and repeat a visual pattern",["Adult draws a large rectangle for the flag.","Choose 2 colors.","Draw a stripe in Color 1 and then Color 2.","Repeat the two-color pattern across the flag.","Add one large shape in the center."],"Start the first two stripes and let the student copy them.","Make 4 wide stripes using 2 colors.","Use a 3-color ABC pattern and add a symbol.","This is finished when the flag contains a repeated color pattern and one center shape.")),
 detailed(t("four_box_comic","Draw a 4-Box Classroom Comic",["Practice","Stretch"],["paper","pencils","crayons"],20,"Create a simple visual story in order",["Fold or divide paper into 4 boxes.","Draw a character entering class in Box 1.","Draw the character choosing a task in Box 2.","Draw the character working in Box 3.","Draw the character finishing in Box 4."],"Accept stick figures and let the adult describe each box first.","Use 2 boxes: start and finish.","Add one speech bubble or short sentence to every box.","This is finished when the 4 drawings show a clear beginning, middle, and ending.")),
 detailed(t("color_number_grid","Color a Number Grid",["Regulate & Focus","Participate","Practice"],["paper","pencils","crayons"],20,"Follow a color key and complete a design",["Adult draws a 4-by-4 grid and writes 1, 2, or 3 in every box.","Make a key: 1 is red, 2 is blue, and 3 is yellow.","Find one numbered box at a time.","Color each box using the key.","Check that all 16 boxes are colored."],"Use a 3-by-3 grid with numbers 1 and 2.","Color 9 boxes using 2 colors.","Create a new color key and grid for the adult to complete.","This is finished when every numbered box matches the color key.")),
 detailed(t("block_maze","Build a Block Path Through a Maze",["Participate","Practice","Stretch"],["blocks","paper","pencils"],20,"Plan and build a path from start to finish",["Adult draws a large START dot and FINISH star on paper.","Place 6 blocks between the dot and star as obstacles.","Use 10 more blocks to make a path around the obstacles.","Move one small block along the path from START to FINISH.","Draw the finished path."],"Use 3 obstacles and let the adult begin the path.","Build one clear path around 3 blocks.","Build a second, shorter path and compare the two.","This is finished when a block can travel from START to FINISH without touching an obstacle.")),
 detailed(t("clay_scene","Build a Clay Classroom Scene",["Participate","Practice","Stretch"],["clay or Play-Doh","paper","pencils"],20,"Build and describe a familiar scene",["Make 1 clay person.","Make 1 clay table.","Make 1 clay chair.","Place the person beside the table and chair.","Draw the scene on paper and point to each object."],"Adult makes one model object first.","Make a person and one classroom object.","Add 3 more objects and describe where each one is located.","This is finished when the scene contains a person, table, chair, and matching drawing.")),
 detailed(t("counter_picture","Make a Picture with 20 Counters",["Regulate & Focus","Participate","Practice"],["counters","paper","pencils"],20,"Arrange objects to create a recognizable picture",["Get exactly 20 counters.","Choose to make a face, flower, house, or number.","Arrange all 20 counters on paper to make the picture.","Trace around several counters with a pencil.","Count the counters again before cleaning up."],"Offer two picture choices and begin the outline.","Use 10 counters to make a simple face.","Make a second picture using the same 20 counters in a new arrangement.","This is finished when all 20 counters form one recognizable picture and are recounted.")),
 detailed(t("paper_chain_pattern","Make a 12-Link Paper Pattern",["Participate","Practice"],["paper","scissors","crayons","glue"],20,"Create a tactile repeating pattern",["Adult cuts 12 paper strips.","Color 6 strips red and 6 strips blue.","Make one red strip into a loop and glue it.","Place a blue strip through the loop and glue it.","Continue red-blue until all 12 links are connected."],"Adult cuts and starts the first two links.","Make a 6-link chain.","Use 3 colors in an ABC pattern.","This is finished when 12 links form one red-blue repeating chain.")),
 detailed(t("make_ten_cards","Find 8 Card Pairs That Make 10",["Practice","Stretch"],["playing cards","paper","pencils"],20,"Use addition combinations strategically",["Remove face cards and use A as 1.","Place number cards face up.","Find 2 cards that add to 10.","Write the addition sentence on paper.","Continue until 8 pairs have been found and recorded."],"Provide one example such as 4 and 6.","Find 4 pairs that make 10.","Find pairs that make 12 or use 3 cards to make 10.","This is finished when 8 correct pairs and equations are recorded.")),
 detailed(t("grid_route","Plan the Shortest Grid Route",["Practice","Stretch"],["paper","pencils","counters"],20,"Plan, test, and compare routes",["Adult draws a 5-by-5 grid with START in the bottom-left and FINISH in the top-right.","Place 5 counters on squares as blocked spaces.","Draw a route that moves only up, down, left, or right.","Count the squares in the route.","Try a second route and circle the shorter one."],"Use a 3-by-3 grid with 1 blocked square.","Draw one working route.","Create a maze for the adult and check the adult's route.","This is finished when two valid routes are counted and the shorter route is circled.")),
 detailed(t("tower_rule","Solve 6 Block Tower Rules",["Practice","Stretch"],["blocks","paper","pencils"],20,"Use clues to build the correct tower",["Adult gives Rule 1: build a tower taller than 3 blocks but shorter than 6.","Build one tower that follows the rule.","Draw it and write its height.","Complete 5 more adult-given rules.","Check every tower against its rule."],"Use rules with one condition, such as build exactly 3.","Complete 3 simple rules.","Have the student write 3 tower rules for the adult.","This is finished when 6 towers are built, drawn, and checked against 6 rules.")),
 detailed(t("pattern_detective","Be a Pattern Detective",["Practice","Stretch"],["paper","pencils","crayons"],20,"Identify and explain pattern rules",["Adult draws 6 patterns with one mistake in each.","Look at Pattern 1 and circle the item that breaks the rule.","Draw the correct item above it.","Repeat for all 6 patterns.","Tell or show the rule for one pattern."],"Use simple AB patterns and point to two possible answers.","Correct 3 AB patterns.","Create 3 mistake patterns for the adult to solve.","This is finished when all 6 mistakes are circled and corrected.")),
]

MODE_INFO={"Regulate & Focus":"Short, calm tasks for attention, communication, and readiness.","Participate":"Simple hands-on tasks with choices and adult guidance.","Practice":"Academic or classroom-skill practice with a clear product.","Stretch":"More independent, multi-step tasks with optional sports/math connections."}

def compatible(mode,materials,minutes,strict_mode=False):
    items=[x for x in TASKS if x["minutes"]<=minutes and (not strict_mode or mode in x["modes"])]
    if materials: items=[x for x in items if set(x["materials"]).issubset(set(materials))]
    return items

def extension_options(item):
    task_id=item["id"]
    title=item["title"]
    if any(word in task_id for word in ["dice","score","high_card"]):
        return [item["hard"],"Complete 5 more rounds and add the new results to the same recording page.","Compare the first set with the second set and circle what changed."]
    if any(word in task_id for word in ["card","number_line","sticky_line"]):
        return [item["hard"],"Mix the cards or notes and complete the activity a second time without looking at the first arrangement.","Have the student give the adult directions for putting the numbers in the correct order."]
    if "clay" in task_id or task_id=="emotion_faces":
        return [item["hard"],"Make a second set using different sizes, shapes, letters, or numbers.","Draw and label the finished clay models on paper before putting the clay away."]
    if any(word in task_id for word in ["measure","paper_strips","book_sort","pencil_sort"]):
        return [item["hard"],"Choose 3 additional classroom objects and add them to the comparison.","Put every result in order and find the difference between the smallest and largest measurement."]
    if any(word in task_id for word in ["sort","graph","frequency","tally","categories","folder","coin"]):
        return [item["hard"],"Repeat the activity with a new set of 10 objects or a new category rule.","Use the completed counts to make a two-column comparison or a simple bar graph."]
    if any(word in task_id for word in ["block","counter","groups","ten_frame","eraser","more_less","roll_build"]):
        return [item["hard"],"Repeat the task with 5 more objects or with one additional group.","Draw the completed model and write the number represented by each group."]
    if any(word in task_id for word in ["draw","trace","path","shape","pattern","collage","number_trace","target","picture"]):
        return [item["hard"],"Make a second page using different colors, shapes, numbers, or directions.","Ask the student to point to each part and tell, sign, or show the adult what was completed."]
    return [item["hard"],f"Repeat “{title}” with a new set of numbers, colors, or classroom objects.","Let the student teach the adult how to complete one part of the activity."]

def task_visual(item):
    task_id=item["id"]
    materials=set(item["materials"])
    if "dice" in task_id or "score" in task_id or task_id=="roll_build": return "🎲 ✏️ 🔢"
    if "clay" in task_id or task_id=="emotion_faces": return "🟠 🔺 🙂"
    if "card" in task_id or task_id in {"red_black","high_card"}: return "🃏 1️⃣ 2️⃣"
    if "measure" in task_id or task_id in {"paper_strips","book_sort","pencil_sort"}: return "📏 ✏️ ↔️"
    if "graph" in task_id or "frequency" in task_id or "tally" in task_id or "folder" in task_id: return "📊 ✏️ ✅"
    if "sort" in task_id or "categories" in task_id or "coin" in task_id: return "🔴 🔵 🟡"
    if "block" in task_id or "blocks" in materials: return "🧱 1️⃣ 2️⃣"
    if "counter" in task_id or "groups" in task_id or "ten_frame" in task_id or "eraser" in task_id: return "🔵 🔵 🔵"
    if "pattern" in task_id: return "🔴 🔵 🔴 🔵"
    if "path" in task_id: return "● 〰️ ⭐"
    if "choice" in task_id or "collage" in task_id: return "🎨 🔢 ❤️"
    if "shape" in task_id or "target" in task_id: return "🔵 🟥 🔺"
    if "number" in task_id or "dot" in task_id or "sticky_line" in task_id: return "1️⃣ 2️⃣ 3️⃣"
    if "sequence" in task_id or "picture" in task_id: return "1️⃣ ➡️ 2️⃣ ➡️ 3️⃣"
    if "draw" in task_id or "trace" in task_id: return "✏️ 🖍️ 📄"
    if "reset" in task_id or "breathe" in task_id: return "🌬️ 🙂 🌈"
    if "paper" in materials or "pencils" in materials: return "📄 ✏️ 🖍️"
    return "🧩 ⭐ ✅"

STYLE_OPTIONS=["Creative","Tactile / Hands-On","Strategic / Problem-Solving"]

def task_styles(item):
    task_id=item["id"]
    materials=set(item["materials"])
    styles=[]
    creative_words=["draw","color","clay","collage","design","flag","comic","picture","shape","pattern","trace","path","jersey","scene"]
    tactile_materials={"clay or Play-Doh","blocks","counters","buttons or counters","erasers or counters","playing cards","dice","sticky notes","coins","classroom objects","scissors","glue"}
    strategic_words=["dice","card","score","compare","graph","frequency","tally","sort","measure","groups","ten_frame","route","rule","detective","order","sequence","maze","make_ten"]
    if any(word in task_id for word in creative_words) or {"crayons","markers"}&materials:
        styles.append("Creative")
    if materials&tactile_materials or any(word in task_id for word in ["build","counter","block","clay","sort","chain"]):
        styles.append("Tactile / Hands-On")
    if any(word in task_id for word in strategic_words) or item["goal"].lower().find("plan")>=0:
        styles.append("Strategic / Problem-Solving")
    if not styles:
        styles.append("Creative")
    return [style for style in STYLE_OPTIONS if style in styles]

def card(item,n):
    preview="".join(f"<li>{step}</li>" for step in item["steps"][:3])
    visual=task_visual(item)
    style_pills="".join(f"<span class='pill'>{style}</span>" for style in task_styles(item))
    return f"<div class='choice'><div class='task-visual' role='img' aria-label='Picture clue for {item['title']}'>{visual}</div><span class='pill'>{item['minutes']} min</span>{style_pills}<h3>{n}. {item['title']}</h3><p><b>Get:</b> {', '.join(item['materials'])}</p><p><b>Start by doing this:</b></p><ol>{preview}</ol><p><b>Finished when:</b> {item['finish']}</p></div>"

st.markdown("<div class='hero'><h1>🧩 Ready, Set, Choose!</h1><p>A flexible classroom activity tool for choosing a task that fits today.</p><p>The adult chooses the readiness mode. The student still gets meaningful choices.</p></div>",unsafe_allow_html=True)
st.sidebar.header("👩‍🏫 Adult Setup")
mode=st.sidebar.selectbox("Today’s readiness mode",list(MODE_INFO),key="mode")
st.sidebar.info(MODE_INFO[mode])
minutes=st.sidebar.slider("Available time",15,30,20,step=5)
all_materials=sorted({m for x in TASKS for m in x["materials"]})
show_sports=st.sidebar.checkbox("Show sports/math connections",value=True)
student=st.sidebar.text_input("Student name or initials (optional)")

st.markdown("### Student choice")
st.write("Choose one of the activities below. You can change your mind before starting.")
suggested_difficulty={"Regulate & Focus":0,"Participate":0,"Practice":1,"Stretch":2}[mode]
task_version=st.sidebar.radio("Task difficulty for today",["Easier","Standard","Challenge"],index=suggested_difficulty,key=f"task_version_{mode}",help="This changes the task demand without labeling the student.")
today_styles=st.sidebar.multiselect("Today’s activity style — required",STYLE_OPTIONS,default=[],help="The aide or teacher must choose at least one style before tasks appear. Choose multiple styles for a mixed set.")
if not today_styles:
    st.info("👩‍🏫 Adult setup: Select at least one **Today’s activity style** in the sidebar before student task choices appear.")
    st.stop()
style_signature=(mode,tuple(sorted(today_styles)))
if st.session_state.get("style_signature")!=style_signature:
    st.session_state.style_signature=style_signature
    st.session_state.pop("selected",None)
    st.session_state.seed=random.randrange(100000)
strict_mode=st.sidebar.checkbox("Only show tasks originally designed for this readiness mode",value=False,help="Leave this off for the largest variety. Turn it on when you want a narrower list.")
materials=st.sidebar.multiselect("Only show tasks using these materials (optional)",all_materials,default=[],key="material_filter",help="Leave this empty to see every task for the selected readiness mode.")
options=compatible(mode,materials,minutes,strict_mode)
if today_styles:
    options=[item for item in options if set(task_styles(item))&set(today_styles)]
if not options:
    st.warning("No tasks match every selected filter. Add a material or increase the time.")
    st.stop()
choice_count=st.sidebar.slider("Number of student choices",3,12,min(9,max(3,len(options))))
st.caption(f"Showing up to {choice_count} choices from {len(options)} activities. Each has an Easier, Standard, and Challenge version.")
if "seed" not in st.session_state: st.session_state.seed=random.randrange(100000)
if st.button("🔄 Show different choices",use_container_width=True): st.session_state.seed=random.randrange(100000)
shown=random.Random(st.session_state.seed).sample(options,min(choice_count,len(options)))
for row_start in range(0,len(shown),3):
    cols=st.columns(3)
    for offset,item in enumerate(shown[row_start:row_start+3]):
        n=row_start+offset+1
        with cols[offset]:
            st.markdown(card(item,n),unsafe_allow_html=True)
            if st.button(f"Choose {n}",key=f"choose_{item['id']}",use_container_width=True): st.session_state.selected=item["id"]

selected=next((x for x in TASKS if x["id"]==st.session_state.get("selected")),None)
if selected is None:
    st.info("Choose an activity to see the directions.")
    st.stop()
st.markdown("---")
st.markdown(f"<div class='panel'><div class='task-visual' role='img' aria-label='Picture clue for {selected['title']}'>{task_visual(selected)}</div><h2>✅ {selected['title']}</h2><p><b>Activity style:</b> {', '.join(task_styles(selected))}</p><p><b>Goal:</b> {selected['goal']}</p><p><b>Materials:</b> {', '.join(selected['materials'])}</p><p><b>You are finished when:</b> {selected['finish']}</p></div>",unsafe_allow_html=True)
if task_version=="Easier":
    st.success(f"**Use the easier version today:** {selected['easy']}")
elif task_version=="Challenge":
    st.success(f"**Use the challenge version today:** {selected['hard']}")
else:
    st.success("**Use the standard version today:** Follow the numbered steps exactly as written.")
st.markdown("### Steps for the student")
for n,step in enumerate(selected["steps"],1): st.markdown(f"<div class='step'><b>{n}.</b> {step}</div>",unsafe_allow_html=True)
st.markdown("### Adult support")
st.markdown(f"<div class='adult'>{selected['adult']}</div>",unsafe_allow_html=True)
if show_sports: st.info(f"🏅 Optional connection: {selected['link']}")
st.markdown("### Adult pacing and adaptations")
st.info("**Suggested 15–20 minute plan:** 2–3 minutes to gather materials and model the task, 8–10 minutes for the main activity, and 5–8 minutes for an extension or a second round.")
with st.expander("Adjust the level or add time",expanded=True):
    st.write(f"**If the task is too much today:** {selected['easy']}")
    st.write("**If the task is a good fit:** Complete the numbered steps, check the finished work together, and have the student point to or show one completed part.")
    st.write(f"**If the student is ready for a higher level:** {selected['hard']}")
    st.write("**If the student finishes early, choose one or more:**")
    for option in extension_options(selected):
        st.write(f"- {option}")

st.markdown("### Quick check-in")
status=st.radio("How did it go?",["Not started","Working","Finished","Needed a break"],horizontal=True)
notes=st.text_area("Optional adult note",placeholder="What helped? What should we try next time?")
if st.button("✅ Save today’s check-in",use_container_width=True):
    st.session_state.last_checkin={"date":date.today().isoformat(),"student":student or "Student","mode":mode,"difficulty":task_version,"task":selected["title"],"status":status,"notes":notes}
    st.success("Today’s check-in was saved for this session.")
if st.session_state.get("last_checkin"):
    x=st.session_state.last_checkin
    st.caption(f"Last check-in: {x['task']} · {x['status']} · {x['date']}")
